In [49]:
from lib.TaxiEnv import TaxiEnv
import numpy as np
from time import time
from lib.utilities import getInverseAction,renderStates
env = TaxiEnv()
env.print = False

In [63]:
def dfs (env, start, maxDepth = 15 ,moreResults = False):
    #for k in range(env.allStatesCount):
    statesTisTurn = []

    statesTisTurn.append(start)
    states = {}
    genericMaskLen = len(env.getLastActionMask())
    gotResult = False
    goThrough = False
    onBoard = False
    done = False
    solDepth = float("inf")
    finalPath = None
    pickupState = [] 
    stuckCounter = 0
    #For every pre-fetched actions
    while not gotResult:
        #print(statesTisTurn)
        #print("")

        #If we are stuck in this cycle
        if(stuckCounter > 3):
            return finalPath

        while len(statesTisTurn) > 0:
        
            i = statesTisTurn.pop()
            #print(i,end=",")
            state, actionMask = env.setState(i, True)
            if not (state in states):
                states[state] = [False,0,[]]
            #If we got to the max depth, end this turn

            print("----------------")
            print(states)
            print(state)
            if(states[state][1] > maxDepth or states[state][1] > solDepth):
                continue
            
            # For each action:
            print(actionMask)
            for actionId in range(genericMaskLen):
                actionId = 5 - actionId        
                
                #If action is not viable skip
                if(actionMask[actionId]) == 0:
                    continue
                print(actionId)
                #Else :
                #Set the previous state:
                env.setState(i)
                #Make a move
                nxtState, rew, done ,_,_ = env.move(actionId)
                #If the action was "pickup" - start from here next itteration
                if(actionId == 4):
                    # statesTisTurn = []
                    # statesNextTurn = []
                    pickupState = nxtState
                    #Reset current Depth:

                    solDepth = states[state][1]+1
                    #states[state][1] = 0
                    
                    #onBoard = True
                    #statesNextTurn = [nxtState]
                #If I am done - return with the path
                if(done):
                    #print(2)
                    pickupState = nxtState
                    finalPath = states[state].copy()
                    finalPath[2].append(state)
                    finalPath[2].append(nxtState)
                    gotResult = True
                    # if(moreResults):    
                    #     return finalPath
                    # return finalPath[2]    
                    break
                #If we have the passenger onboard but the action doesn't make it "done" - end
                elif(actionId == 5):
                    continue
                #If next state hasn't been checked - add an empty array
                if not (nxtState in states):
                    states[nxtState] = [False,0,[]]
                    goThrough = True
                #If the nextState hasn't been searched or shorter path has been found
                if goThrough or onBoard != states[nxtState][0]  or (len(states[nxtState][2]) > len(states[state][2])+1 ) :
                    goThrough = False
                    #print(rew)
                    states[nxtState][2] = states[state][2].copy()
                    states[nxtState][2].append(state)
                    states[nxtState][1] = states[state][1]+1
                    states[nxtState][0] = onBoard
                    statesTisTurn.append(nxtState)
                #else:
                    #print("Not updated - " + str(nxtState) + " from state " + str(state))
        else:
            if(gotResult):
                break
            #print("yes")
            #break
            #statesTisTurn = statesNextTurn.copy()
            #print(statesNextTurn)q
            onBoard = True
            solDepth = float("inf")
            statesTisTurn = [pickupState]
            print(states)
            print(pickupState)
            states[pickupState][1] = 0
        stuckCounter += 1

    
    if(moreResults):    
        return finalPath
    return finalPath[2]               


In [51]:
# env.setState(137)
# env.printCurState()

In [68]:
dfs(env,3)

----------------
{3: [False, 0, []]}
3
[1 0 1 0 1 0]
4
2
0
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]]}
103
[1 1 1 0 0 0]
2
1
0
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]], 123: [False, 2, [3, 103]], 203: [False, 2, [3, 103]]}
203
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]], 123: [False, 2, [3, 103]], 203: [False, 2, [3, 103]]}
123
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]], 123: [False, 2, [3, 103]], 203: [False, 2, [3, 103]]}
23
[1 0 0 1 0 0]
3
0
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]], 123: [False, 2, [3, 103]], 203: [False, 2, [3, 103]]}
19
[1 0 1 0 0 1]
5
2
0
----------------
{3: [False, 0, []], 19: [False, 1, [3]], 23: [False, 1, [3]], 103: [False, 1, [3]], 123: [False, 2, [3, 103]], 203: [False, 2, 

[3, 19, 119, 219, 239, 259, 279, 379, 479, 475]

In [65]:
from time import sleep
for i in range(500):
    env = TaxiEnv()
    env.print = False
    
    ret = dfs(env,i)
    print(ret)
    #renderStates(ret)
    sleep(2)

----------------
{0: [False, 0, []]}
0
[1 0 1 0 1 0]
4
2
0
----------------
{0: [False, 0, []], 16: [False, 1, [0]], 20: [False, 1, [0]], 100: [False, 1, [0]]}
100
[1 1 1 0 0 0]
2
1
0
----------------
{0: [False, 0, []], 16: [False, 1, [0]], 20: [False, 1, [0]], 100: [False, 1, [0]], 120: [False, 2, [0, 100]], 200: [False, 2, [0, 100]]}
200
----------------
{0: [False, 0, []], 16: [False, 1, [0]], 20: [False, 1, [0]], 100: [False, 1, [0]], 120: [False, 2, [0, 100]], 200: [False, 2, [0, 100]]}
120
----------------
{0: [False, 0, []], 16: [False, 1, [0]], 20: [False, 1, [0]], 100: [False, 1, [0]], 120: [False, 2, [0, 100]], 200: [False, 2, [0, 100]]}
20
[1 0 0 1 0 0]
3
0
----------------
{0: [False, 0, []], 16: [False, 1, [0]], 20: [False, 1, [0]], 100: [False, 1, [0]], 120: [False, 2, [0, 100]], 200: [False, 2, [0, 100]]}
16
[1 0 1 0 0 1]
5
[0, 16, 0]
----------------
{1: [False, 0, []]}
1
[1 0 1 0 1 0]
4
2
0
----------------
{1: [False, 0, []], 17: [False, 1, [1]], 21: [False, 1, [1]],

KeyboardInterrupt: 

In [66]:
dfs(env,16)

----------------
{16: [False, 0, []]}
16
[1 0 1 0 0 1]
5


[16, 0]

In [67]:
renderStates(dfs(env,16))

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+




In [58]:
env.setState(16)
env.printCurState()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+


